Add HTML, CSS, and JAVASCRIPT files
mosidrum/Capstone_project_1 pull request #1
Opened 2023-04-20 10:05 UTC by mosidrum

I have successfully done the following: 

- Created a home page
- Created about page
-  Implement responsivity for the home page & about page by using media queries
-  Used Javascript to create dynamic sections and mobile menu on both pages on small device

2023-04-20 17:01 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @mosidrum , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media4.giphy.com/media/Ph7tOzOVfMypwbpcUZ/giphy.gif"/>

## Highlights
- Project matches given wireframe :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
- Contents personalized :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Informative video presentation :heavy_check_mark: 
- Professional README :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-20 17:01 UTC, nahnahdev commented on README.md
> +<!-- - [Live Demo Link]() -->
- [ ] Good job so far @mosidrum Your project looks great :100: There are just a few changes you need to make and you'll be on your way to the next module :wink: 
- [ ] First of all, I will suggest that you use `GitHub Pages ` to deploy your project and ensure that your project is deployed properly and that all pages, links, and images work as expected. :100: After this, you should include a link to to the deployed project in the README. :wink:

2023-04-20 17:01 UTC, nahnahdev commented on index.html
> +        <div class="right">
- [ ] I want to start by saying that this section of your Home Page looks great! However, I would suggest that you reduce the spacing between the cards to match the original design, as this will help maintain consistency with the rest of the page. :+1: 
- [ ] Additionally, I noticed that the hover effects on the cards are missing. Please consider adding these effects as shown in the design, as they can help improve the interactivity and user experience of the page :+1: 

| Behance Design | Your Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/233415594-80fab8ed-6abf-42c1-8486-2f128eb90391.png) | ![image](https://user-images.githubusercontent.com/102699958/233415723-644365ef-4da8-44e9-ab57-494127e4faa4.png) |

2023-04-20 17:01 UTC, nahnahdev commented on index.html
> +    <hr class="line">
- [ ] I noticed that the horizontal line under the heading `Featured Speakers` needs to be styled to match the design provided. Please make the necessary changes to ensure that the line looks similar to the design. This will help maintain consistency with the rest of the page and improve the overall visual appeal:100: 
- [ ] Kindly ensure that these style adjustments are applied to the mobile view as well :100: 

| Your Design | Behance Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/233417145-0ff405ad-9f9d-4b1c-b56c-91ddd83aa701.png) | ![image](https://user-images.githubusercontent.com/102699958/233417222-7760ce80-aa3c-4fe4-b72f-42d05becd6e5.png) |

2023-04-20 17:01 UTC, nahnahdev commented on index.html
> +    </div>
- [ ] Great job on this section so far! I noticed that the **'Partners' section** is currently wrapped in a (`div `tag). Since this section is intended to contain only partners, it would be better to wrap it in a (`section` tag) instead. This will help improve the semantics and organization of the HTML code :+1: 
- [ ] I noticed that the partner logos are currently smaller than the ones in the original design. To improve the visual consistency with the design, I suggest increasing the size of each partner logo slightly. This will help them stand out more and make the overall design look more polished.:+1: 
- [ ] I noticed that the left and right edges of the **Partners section** are currently white, which is different from the dark background color used in the original design. To make the section more consistent with the design, you could adjust the CSS properties of the section element to ensure it fits the container 100%. This will stretch the section to fill the full width of its container, and ensure that the background color of the section extends all the way to the edges of the screen, creating a more cohesive design:wink: 

- Your Design
![image](https://user-images.githubusercontent.com/102699958/233421263-641013bd-3f82-4169-aec1-fb8f0d8a3a03.png)

- The Behance design
![image](https://user-images.githubusercontent.com/102699958/233421547-3b2fd386-d449-401e-89f8-ca4e39476a87.png)

2023-04-20 17:01 UTC, nahnahdev commented on about.html
> +      <hr>
- [ ] I noticed that there is not enough spacing between the end of the first `div` and the second `div` on the About page. I would suggest that you increase the spacing between the two divs so they don't look as close together. This will create a more balanced design that is similar to the original design.:100: 
- [ ] To maintain consistency in the design, it's important to ensure that the containers of the design elements extend to the edge of the main container. This will prevent the edges from having a different color and ensure that the background color is consistent throughout the page, making the design look cohesive. :+1: 
- [ ] Kindly ensure that these style adjustments are applied to the mobile view as well :100: 

- Your Design
![image](https://user-images.githubusercontent.com/102699958/233426213-bfc54603-c5cb-49c0-9b07-bb2c378b2bc4.png)

- The Figma Design
![image](https://user-images.githubusercontent.com/102699958/233426477-038afa9d-4ff6-4e2a-b122-7217cb050d16.png)

2023-04-20 17:01 UTC, nahnahdev commented on index.html
> +        <h1 class="animate">KING'S WORD MID-YEAR MUSICAL CONCERT <br>2023</h1>
- [ ] Your page heading looks great but it hasn't been styled as seen in the Figma Design. However per the style guidelines, 
- Your pages should look almost identical to the original design, outside the content differences.
- Your pages use the exact same colors, for text, backgrounds, borders, etc, from the original design. 
- [ ] As a result of this, you need to ensure that your design has similar colors as seen in the design as well as the font weight :+1: 
- [ ] Kindly ensure that these style adjustments are applied to the mobile view as well :100: 

| Your Design | The Behance Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/233411760-24930681-dba9-4b9d-9062-0aab2404d2ea.png) | ![image](https://user-images.githubusercontent.com/102699958/233411633-a8b07274-c9d8-47c9-ad38-8101df8da8e9.png)
 |

2023-04-20 17:01 UTC, nahnahdev commented on index.html
> +      <p class="main-text">Get ready London for the biggest concert of the year in worship and praise to God your father, no sermons, no prayers, just Music! Music!! Music!!. There is a sound that co
- [ ] I will suggest that you remove the background color that you applied to this text so your design looks similar to the given design :100: 
- [ ] From the design you can see that the background color of that text is the same as the background image color of the main section so all you need to do is to remove the dark background you've applied and you'll be fine :100: 
- [ ] Kindly ensure that these style adjustments are applied to the mobile view as well :100: 

| Your Design | Behance Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/233414277-d893f5ce-a55a-49d8-b40a-d10b4aa6f441.png) | ![image](https://user-images.githubusercontent.com/102699958/233414408-4c6487ff-b660-4f33-ad7d-7d3d7ab8f9ef.png) | 

- [ ] For the mobile view, I noticed there is a white gap below the main section, which creates a visual inconsistency in the background color. To fix this, I suggest ensuring that the section's background color extends all the way to the bottom of the screen. Additionally, I recommend increasing the spacing between this section and the next one to match the original design :wink: 

- Your Design
![image](https://user-images.githubusercontent.com/102699958/233434844-1954d59b-af82-4494-a2db-608ac5ee22ed.png)

- The Behance Design
![image](https://user-images.githubusercontent.com/102699958/233434926-105397e4-d076-414a-9e2a-1147279afd85.png)

2023-04-20 17:01 UTC, nahnahdev commented on about.html
> +    </div>
- [ ] Lastly, I will suggest that you increase the spacing around the images container so your design looks similar to the original design 
- [ ] Also as I mentioned earlier I noticed that the left and right edges of the **Footer section** are currently white, which is different from the dark background color used in the original design. To make the section more consistent with the design, you could adjust the CSS properties of the section element to ensure it fits the container 100%. This will stretch the section to fill the full width of its container, and ensure that the background color of the section extends all the way to the edges of the screen, creating a more cohesive design :+1: 
- [ ] Kindly do same for the `Partners section` of the mobile view as well :100: 
- Your Design
![image](https://user-images.githubusercontent.com/102699958/233428689-fa45af5b-f2c8-4742-9535-08d9a1f3b7c5.png)

- The Behance Design
![image](https://user-images.githubusercontent.com/102699958/233429181-955b5419-6eca-4a33-b8d7-948737668856.png)

2023-04-20 17:01 UTC, nahnahdev commented on about.html
> +    <img src="./images/creative-commons.png" alt="creative_commons_logo">
- [ ] The logo you used here is different from your original logo so kindly replace this with the logo you used for this project for consistency :+1: 
- Your About Page
![image](https://user-images.githubusercontent.com/102699958/233436071-0dfa07ba-2196-4eee-a0fe-97caea8dc87d.png)

- Your Home Page
![image](https://user-images.githubusercontent.com/102699958/233436131-dbad5ebd-36f0-4453-aeb6-373d9f396422.png)

2023-04-20 17:01 UTC, nahnahdev commented on about.html
> +    <i class="fa-solid fa-bars" onclick="showMenu()"></i>
- [ ] Kindy give your `mobile-menu` a background color that is either transparent or the same color/pattern as the top section background. :+1: 
- [ ] I noticed that when viewing the About page in the mobile view, there is no way to navigate back to the Home page. To improve the user experience, I suggest replacing the `About` menu item on the mobile menu with `Home` when on the About page. This will provide users with a clear way to navigate back to the Home page.:100: 
- Your Design Now
![image](https://user-images.githubusercontent.com/102699958/233430628-f8309664-56b2-43e7-aa62-f86d474a6bd7.png)

2023-04-21 03:26 UTC, binhussen requested changes
Hi @mosidrum , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 03:26 UTC, binhussen commented on index.html
> +      <section>
- Kindly, reduce the spacing between the cards and add the hover effects on the cards to match the original design and to improve the interactivity and user experience of the page 👍 As the previous code reviewer suggested you 👍
![Uploading 2023-04-21_06-11.png…]()

2023-04-21 03:26 UTC, binhussen commented on index.html
> +        <h1 class="animate">KING'S WORD MID-YEAR MUSICAL CONCERT <br>2023</h1>
- Kindly, Your pages have to use the exact same colors, for text, backgrounds, borders, etc, from the original design as the previous code reviewer suggested to you. use those color swatch: `#272A31`, `#EC5242`, `#D3D3D3` 👌
![2023-04-21_06-12](https://user-images.githubusercontent.com/52010789/233532099-79114fd8-5ff0-447c-9902-4bd9dba026d1.png)

2023-04-21 04:40 UTC, shella12 reviewed
Hi @mosidrum , 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great design Implementation 👏
- Awesome animation effects ✨ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 04:40 UTC, shella12 commented on js/script.js
> +
- [ ] [OPTIONAL] While trying to check responsiveness I encountered a bug. If you click on the hamburger menu and expand the screen to the desktop version, the `navbar` links just move down from their original position. Also if you go back to the mobile version, and close the open hamburger menu and expand the screen back to the desktop version, the nav links disappear entirely. I would highly suggest you to fix this bug as these projects are gonna be used to display on your resume, portfolio, linkedIn etc and left out bugs would indicate that you are lacking attention to detail.

https://user-images.githubusercontent.com/44798044/233542272-f8a82f49-fad8-4d0e-ba3b-49df2f786408.mov

2023-04-21 09:21 UTC, merged